name: Run base code on different python versions
'on': workflow_dispatch 
jobs:
  python_run_scripts:
    strategy:
      matrix:
        python: [3.9.12, 3.10.8, 3.11.10]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }} # install the python version needed
      - run: python install --editable ".[dev]"
