name: Run Tests with Container

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: cpaniaguam/icesat2waves:test
      
jobs:
  test:
    runs-on: ubuntu-latest

    container:
        image: ${{ env.IMAGE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          docker run --volume="${{ github.workspace }}:/app" \
                     --workdir="/app" \
                     ${{ env.IMAGE_NAME }} \
                     python src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py 20190502052058_05180312_005_01 SH_testSLsinglefile2 True
