name: Test B01_SL_load_single_file
on:
  pull_request: {}
  push:
    branches: [ main ]
jobs:
  python_run_scripts:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.9']
    runs-on: ubuntu-latest
    steps:
      - name: install mpi
        run: sudo apt update && sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev 
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }} # install the python version needed
          cache: "pip"
      - name: install icesat2-tracks using pip
        run: pip install .
      - name: install pytest
        run: pip install pytest pytest-xdist
      - name: Run pytest
        run: pytest -n 2 tests
