name: Test B01_SL_load_single_file
on:
  pull_request: {}
  push:
    branches: [ main ]
jobs:
  python_run_scripts:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.11']
    runs-on: ubuntu-22.04
    steps:
      - name: install mpi
        run: sudo apt update && sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev 
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }} # install the python version needed
          cache: "pip"
      - name: install icesat2-tracks using pip
        run: pip install .
      - name: List dependencies
        run: pip list
      - name: first step B01_SL_load_single_file
        run: python src/icesat2_tracks/analysis_db/B01_SL_load_single_file.py --track-name 20190502052058_05180312_005_01 --batch-key SH_testSLsinglefile2 --output-dir ./work
      - name: second step make_spectra
        run: python src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py --track-name SH_20190502_05180312 --batch-key SH_testSLsinglefile2 --output-dir ./work
      - name: third step plot_spectra
        run: python src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py --track-name SH_20190502_05180312 --batch-key SH_testSLsinglefile2 --output-dir ./work
      - name: fouth step IOWAGA threads
        run: python src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py --track-name SH_20190502_05180312 --batch-key SH_testSLsinglefile2 --output-dir ./work
        