name: Test Steps
on:
  pull_request: {}
  push:
    branches: [ main ]
jobs:
  python_run_scripts:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.11']
    runs-on: ubuntu-22.04
    steps:
      - name: install mpi
        run: sudo apt update && sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev 
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }} # install the python version needed
          cache: "pip"
      - name: install icesat2-tracks using pip
        run: pip install .
      - name: List dependencies
        run: pip list
      - name: test icesat2waves app
        run: |
            icesat2waves --help
            icesat2waves load-file --help
            icesat2waves make-spectra --help
            icesat2waves plot-spectra --help
            icesat2waves make-iowaga-threads-prior --help
            icesat2waves make-b04-angle --help # prelim name
            icesat2waves define-angle --help
            icesat2waves correct-separate --help # prelim name

      - name: install pytest
        run: pip install pytest pytest-xdist pytest-sugar pytest-durations
      - name: Run tests
        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
        