name: Test steps
on:
  pull_request: {}
  push:
    branches: [ main ]
jobs:
  python_run_scripts:
    strategy:
      fail-fast: false
      matrix:
        version: ['3.11']
    runs-on: ubuntu-latest
    steps:
      - name: install mpi
        run: sudo apt update && sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev 
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }} # install the python version needed
          cache: "pip"
      - name: install icesat2-tracks using pip
        run: pip install .
      - name: install pytest
        run: pip install pytest pytest-xdist pytest-sugar pytest-durations
      - name: Run tests
        run: pytest --capture=sys --verbose --showlocals --tb=long --numprocesses=auto tests/test_steps.py
      - name: second step make_spectra
        run: python src/icesat2_tracks/analysis_db/B02_make_spectra_gFT.py SH_20190502_05180312 SH_testSLsinglefile2 True
      - name: third step plot_spectra
        run: python src/icesat2_tracks/analysis_db/B03_plot_spectra_ov.py SH_20190502_05180312 SH_testSLsinglefile2 True
      - name: fourth step IOWAGA thredds
        run: python src/icesat2_tracks/analysis_db/A02c_IOWAGA_thredds_prior.py SH_20190502_05180312 SH_testSLsinglefile2 True
      - name: Fifth step B04_angle
        run: python src/icesat2_tracks/analysis_db/B04_angle.py SH_20190502_05180312 SH_testSLsinglefile2 True
